"""Generate every number the paper reports, as LaTeX macros.

Nothing in paper.tex may contain a hand-typed figure. In the LAI project this
discipline caught four wrong values that had been entered by hand and survived
several readings; the same rule applies here.

    python paper/make_numbers.py     ->  paper/numbers.tex

Run from the repository root.
"""

import json
from pathlib import Path

import numpy as np

RESULTS = Path("results")
OUT = Path("paper/numbers.tex")
MACROS = {}

# These files are regenerated from results/ and are also pushed to Overleaf,
# where they can be hand-edited in a browser and silently overwritten on the
# next run. The header is the only warning a reader gets there.
HEADER = ("% Generated by paper/make_numbers.py from results/*.json.\n"
          "% Do not edit by hand: the next run overwrites this file.\n")


def add(name, value):
    if name in MACROS:
        raise SystemExit(f"duplicate macro: {name}")
    MACROS[name] = value


def load(name):
    return json.loads((RESULTS / name).read_text())


def sd(v):
    return np.std(v, ddof=1) if len(v) > 1 else 0.0


# The paper says "all measurements use N seeds", so N has to come from the
# results rather than from a typed word: adding seeds to one experiment and
# not the others must break the build, not quietly leave the claim standing.
WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
         7: "seven", 8: "eight", 9: "nine", 10: "ten"}


def _seed_count():
    counts = {f: len({r["seed"] for r in load(f) if "seed" in r})
              for f in TRAINED}
    distinct = set(counts.values())
    if len(distinct) != 1:
        raise SystemExit(
            "the paper claims one seed count for all measurements, but the "
            "results disagree; say so per experiment instead:\n  "
            + "\n  ".join(f"{f}: {n}" for f, n in sorted(counts.items())))
    n = distinct.pop()
    return WORDS.get(n, str(n))


def reach_worth(rows, norm, lo, hi, key="retrained"):
    """Per-seed difference between the largest and smallest reach."""
    seeds = sorted({r["seed"] for r in rows})
    out = []
    for s in seeds:
        a = [r[key] for r in rows if r["norm"] == norm and r["seed"] == s
             and r["prefix"] == lo]
        b = [r[key] for r in rows if r["norm"] == norm and r["seed"] == s
             and r["prefix"] == hi]
        if a and b:
            out.append(b[0] - a[0])
    return np.array(out)


# ---------------------------------------------------------------- setup
add("nParams", "226{,}177")
add("window", "4096")
add("trainSeq", "3840")
add("evalSeq", "512")
add("reachMin", "9")
add("reachMax", "2049")
add("reachFold", "227")
# Receptive field of the three-block prefix (dilations 1, 2, 4): the smallest
# computed bound above the U-Net's shallowest reach, which Section 5 brackets.
add("reachBracketHi", str(1 + 4 * (1 + 2 + 4) + 4))
add("nParamsLo", "26{,}497")
add("paramFold", "8.5")
# Named explicitly rather than globbed. Globbing has twice silently inflated
# this count when a new analysis file landed in results/ -- an exact-optima
# table and a label-statistics file, neither of which trains anything. Every
# file below holds one trained-and-evaluated network per row.
TRAINED = ["tradeoff.json", "tracts_generations.json", "tracts_norms.json",
           "synth.json", "synth_dilated_cnn.json", "synth_tasnet.json",
           "synth_transformer.json", "real_norm.json", "arch_plain_cnn.json",
           "arch_transformer.json", "port_check.json", "unet.json"]
_unused = sorted({f.name for f in RESULTS.glob("*.json")} - set(TRAINED))
assert _unused == ["exposure_survey.json", "jacobian_check.json",
                   "null_deff.json", "optima.json", "shift_null.json",
                   "signal_check.json"], \
    f"unclassified result files: {_unused}"
add("numExperiments", str(sum(len(load(f)) for f in TRAINED)))
add("nSeeds", _seed_count())

# ------------------------------------------------- factorial across difficulty
tr = load("tradeoff.json")
levels = sorted({r["split_time"] for r in tr}, reverse=True)
ratios, fsts = [], []
for T in levels:
    h = [r for r in tr if r["split_time"] == T]
    g = reach_worth(h, "group", 1, 9).mean()
    p = reach_worth(h, "positionwise", 1, 9).mean()
    ratios.append(p / g)
    fsts.append(np.mean([r["fst"] for r in h]))
add("factRatioLo", f"{min(ratios):.1f}")
add("factRatioHi", f"{max(ratios):.1f}")
add("factFstLo", f"{min(fsts):.3f}")
add("factFstHi", f"{max(fsts):.2f}")
add("factFstFold", f"{max(fsts) / min(fsts):.0f}")
add("factLevels", str(len(levels)))
# The range of reach worth across the difficulty sweep. Distinct from
# normGroup/normPos, which are one cell of the pooling-axis experiment; quoting
# those two alongside the 5-level ratio range reads as though the range came
# from them.
_g = [reach_worth([r for r in tr if r["split_time"] == T], "group", 1, 9).mean()
      for T in levels]
_p = [reach_worth([r for r in tr if r["split_time"] == T], "positionwise", 1, 9).mean()
      for T in levels]
add("sweepGroupLo", f"{min(_g):+.4f}")
add("sweepGroupHi", f"{max(_g):+.4f}")
add("sweepPosLo", f"{min(_p):+.4f}")
add("sweepPosHi", f"{max(_p):+.4f}")


def _oxford(xs):
    """"a, b and c" rather than "a, b, c", so a reader can see where a list ends."""
    return xs[0] if len(xs) == 1 else ", ".join(xs[:-1]) + " and " + xs[-1]

# ------------------------------------------------------- normalization axes
nm = load("tracts_norms.json")
_nw = {}
for key, macro in [("none", "normNone"), ("positionwise", "normPos"),
                   ("instance", "normInst"), ("group", "normGroup"),
                   ("batch", "normBatch")]:
    w = reach_worth(nm, key, 1, 9)
    _nw[key] = w.mean()
    add(macro, f"{w.mean():+.4f}")
    add(macro + "SD", f"{sd(w):.4f}")
# How many times more the same parameter increase buys under per-position
# statistics; quoted in the capacity paragraph of Section 4.2 as a word.
add("capacityFold", WORDS[round(_nw["positionwise"] / _nw["group"])] + "fold")

# ------------------------------------------------- dose response, both axes
gen = load("tracts_generations.json")
syn = load("synth_dilated_cnn.json")


def dose(rows, group_key):
    out = []
    for p in sorted({r[group_key] for r in rows}):
        h = [r for r in rows if r[group_key] == p]
        g = reach_worth(h, "group", 1, 9).mean()
        q = reach_worth(h, "positionwise", 1, 9).mean()
        out.append((np.mean([r["switches_per_window"] for r in h]), q / g))
    return out


gd = dose(gen, "generations")
sd_ = dose(syn, "switch_prob")
add("genDoseN", _oxford([f"{n:.2f}" for n, _ in gd]))
add("genDoseRatio", _oxford([f"{r:.1f}" for _, r in gd]))
add("synDoseN", ", ".join(f"{n:.2f}" for n, _ in sd_))
add("synDoseRatio", ", ".join(f"{r:.1f}" for _, r in sd_))
add("synDoseFold", f"{max(n for n, _ in sd_) / min(n for n, _ in sd_):.0f}")
add("synRatioMax", f"{max(r for _, r in sd_):.1f}")
add("synRatioMin", f"{min(r for _, r in sd_):.2f}")
add("synNMin", f"{min(n for n, _ in sd_):.3f}")
add("synNMax", f"{max(n for n, _ in sd_):.1f}")

c = np.array([(r - 1) * n for n, r in sd_])
add("lawC", f"{c.mean():.2f}")
add("lawSpread", f"{100 * sd(c) / c.mean():.0f}")
cm = c[2:6]
add("lawCMid", f"{cm.mean():.2f}")
add("lawSpreadMid", f"{100 * sd(cm) / cm.mean():.0f}")
croot = np.array([(r - 1) * np.sqrt(n) for n, r in sd_])
add("lawRootSpread", f"{100 * sd(croot) / croot.mean():.0f}")

# Ratio at the switch density the other settings sit near, for a like-for-like
# summary table.
match = min(sd_, key=lambda t: abs(t[0] - 0.29))
add("synNMatched", f"{match[0]:.2f}")
add("genNMatched", f"{gd[0][0]:.2f}")
add("tasSwitch", "0.27")

lo_n, lo_r = sd_[0]
h = [r for r in syn if r["switch_prob"] == min(x["switch_prob"] for x in syn)]
add("extremeRatio", f"{lo_r:.1f}")
add("extremeGroup", f"{reach_worth(h, 'group', 1, 9).mean():+.4f}")
add("extremePos", f"{reach_worth(h, 'positionwise', 1, 9).mean():+.4f}")

# ------------------------------- the same densities on an unrelated process
# synth.json runs the Gaussian-Markov process at the switch densities the
# genomic process happens to produce, so the two can be compared point for
# point rather than range against range. Without this the cross-process claim
# rests on curves whose x-values do not line up.
sm = load("synth.json")
_matched = dose(sm, "switch_prob")
add("matchedSynRatios", ", ".join(f"{r:.1f}$\\times$" for _, r in _matched))
add("matchedGenRatios", ", ".join(f"{r:.1f}$\\times$" for _, r in gd))
add("matchedSynN", ", ".join(f"{n:.2f}" for n, _ in _matched))
# The U-Net is run at the sparsest of these densities, so its comparator is
# this run rather than the nearest point of the dense sweep: same density,
# same process, one number rather than two that differ by the run.
add("synRatioMatched", f"{_matched[0][1]:.1f}")

# ------------------------------------ the condition in domain-neutral units
# Switches per 4096-position sequence means nothing outside this task. Mean run
# length is the form a reader in another domain can check their own labels
# against, so the regime boundaries are reported both ways.
_runlen = lambda n: WINDOW_POSITIONS / (n + 1)
WINDOW_POSITIONS = 4096
add("runLenBig", f"{_runlen(3.0):.0f}")     # where the effect is still ~2x
add("runLenGone", f"{_runlen(9.89):.0f}")   # where it has essentially gone
add("runLenDefault", f"{_runlen(gd[0][0]):.0f}")  # the genomic default setting

# ---------------------------------------------------------------- real data
rl = load("real_norm.json")
pref = sorted({r["prefix"] for r in rl})
for key, macro in [("group", "realGroup"), ("positionwise", "realPos")]:
    w = reach_worth(rl, key, pref[0], pref[-1])
    add(macro, f"{w.mean():+.4f}")
    add(macro + "SD", f"{sd(w):.4f}")
add("realRatio", f"{reach_worth(rl, 'positionwise', pref[0], pref[-1]).mean() / reach_worth(rl, 'group', pref[0], pref[-1]).mean():.1f}")
# The ratio's denominator is small, so the mean ratio alone hides seed spread;
# the per-seed range is reported beside it in the text.
_rs = reach_worth(rl, "positionwise", pref[0], pref[-1]) / reach_worth(rl, "group", pref[0], pref[-1])
add("realRatioRound", f"{reach_worth(rl, 'positionwise', pref[0], pref[-1]).mean() / reach_worth(rl, 'group', pref[0], pref[-1]).mean():.0f}")
add("realRatioSeedLo", f"{_rs.min():.0f}")
add("realRatioSeedHi", f"{_rs.max():.0f}")
# Endpoint sensitivity: the pooled family's worth at every intermediate cut,
# against the per-position family's shallowest and full-depth worths. Backs the
# footnote saying no endpoint choice manufactures the contrast.
_gends = [reach_worth(rl, "group", pref[0], k).mean() for k in pref[1:]]
add("realPooledEndLo", f"{min(_gends):+.3f}")
add("realPooledEndHi", f"{max(_gends):+.3f}")
add("realPosEndFirst", f"{reach_worth(rl, 'positionwise', pref[0], pref[1]).mean():+.3f}")
add("realPosEndLast", f"{reach_worth(rl, 'positionwise', pref[0], pref[-1]).mean():+.3f}")
add("realFst", f"{np.mean([r['fst'] for r in rl]):.4f}")
add("realSwitch", f"{np.mean([r['switches_per_window'] for r in rl]):.2f}")
add("realLoAcc", f"{np.mean([r['retrained'] for r in rl if r['norm'] == 'group' and r['prefix'] == pref[0]]):.4f}")
add("realHiAcc", f"{np.mean([r['retrained'] for r in rl if r['norm'] == 'group' and r['prefix'] == pref[-1]]):.4f}")
g = [r for r in rl if r["norm"] == "group" and r["prefix"] == pref[0]]
abl = np.array([r["full"] - r["ablated"] for r in g])
ret = np.array([r["full"] - r["retrained"] for r in g])
add("realAbl", f"{abl.mean():.4f}")
add("realAblSD", f"{sd(abl):.4f}")
add("realRet", f"{ret.mean():.4f}")
add("realRetSD", f"{sd(ret):.4f}")
add("realAblRatio", f"{abl.mean() / ret.mean():.1f}")
# The two estimates differ in noise by much less than they differ in level;
# quoting one factor for both overstates the noise gap.
add("realNoiseFold", f"{sd(abl) / sd(ret):.1f}")
# Accuracy lost at the shortest reach when the length axis is removed. Distinct
# from reach worth, which is a difference across reaches, not across norms.
_g = np.mean([r["retrained"] for r in rl if r["norm"] == "group" and r["prefix"] == pref[0]])
_p = np.mean([r["retrained"] for r in rl if r["norm"] == "positionwise" and r["prefix"] == pref[0]])
add("realShortGap", f"{_g - _p:.4f}")

# -------------------------------------------------------------- Conv-TasNet
tn = load("synth_tasnet.json")
tp = sorted({r["prefix"] for r in tn})
for key, macro in [("gln", "tasGln"), ("cln", "tasCln"), ("gln_pos", "tasPos")]:
    w = reach_worth(tn, key, tp[0], tp[-1])
    add(macro, f"{w.mean():+.4f}")
    add(macro + "SD", f"{sd(w):.4f}")
add("tasGlnRatio", f"{reach_worth(tn, 'gln_pos', tp[0], tp[-1]).mean() / reach_worth(tn, 'gln', tp[0], tp[-1]).mean():.1f}")
_ts = reach_worth(tn, "gln_pos", tp[0], tp[-1]) / reach_worth(tn, "gln", tp[0], tp[-1])
add("tasRatioSeedLo", f"{_ts.min():.0f}")
add("tasRatioSeedHi", f"{_ts.max():.0f}")
add("tasClnRatio", f"{reach_worth(tn, 'gln_pos', tp[0], tp[-1]).mean() / reach_worth(tn, 'cln', tp[0], tp[-1]).mean():.1f}")
add("tasGlnLo", f"{np.mean([r['retrained'] for r in tn if r['norm'] == 'gln' and r['prefix'] == tp[0]]):.4f}")
add("tasCeiling", f"{np.mean([r['bayes_full_context'] for r in tn]):.4f}")
add("tasReachLo", "7")
add("tasReachHi", "1027")
add("tasParams", "226{,}538")

# ------------------------------------------------------------- transformer
tf = load("synth_transformer.json")
diffs, gaps = [], []
for p in sorted({r["switch_prob"] for r in tf}):
    h = [r for r in tf if r["switch_prob"] == p]
    a = np.mean([r["retrained"] for r in h if r["norm"] == "group"])
    b = np.mean([r["retrained"] for r in h if r["norm"] == "positionwise"])
    diffs.append(abs(a - b))
    gaps.append(np.mean([r["bayes_full_context"] for r in h]) - max(a, b))
add("xfDensities", WORDS[len(diffs)])
add("xfDiffLo", f"{min(diffs):.4f}")
add("xfDiffHi", f"{max(diffs):.4f}")
add("xfGap", f"{max(gaps):.4f}")

# --------------------------------------------- the one depth-varying family
# A U-Net pools its statistics over a sequence whose length changes with depth,
# which is the case the criterion and the magnitude could most easily come
# apart in, and the family the prior work names as the practical risk.
un = load("unet.json")
un_depths = sorted({r["depth"] for r in un})
un_lo, un_hi = min(un_depths), max(un_depths)
_rf = lambda d: next(r["receptive_field_conv"] for r in un if r["depth"] == d)
_upar = {r["depth"]: r["n_parameters"] for r in un}
add("unetParamsLo", f"{_upar[un_lo]:,}".replace(",", "{,}"))
add("unetParamsHi", f"{_upar[un_hi]:,}".replace(",", "{,}"))
_umatch = min(_upar, key=lambda d: abs(_upar[d] - 226_177))
add("unetMatchDepth", str(_umatch))
add("unetMatchParams", f"{_upar[_umatch]:,}".replace(",", "{,}"))
add("unetMatchPct", f"{100 * abs(_upar[_umatch] - 226_177) / 226_177:.1f}")
add("unetRFLo", str(_rf(un_lo)))
add("unetRFHi", str(_rf(un_hi)))
add("unetRFFold", f"{_rf(un_hi) / _rf(un_lo):.0f}")
_uw = {r["receptive_field"] for r in un if r["norm"] == "group"}
assert len(_uw) == 1, f"pooled receptive field varies with depth: {sorted(_uw)}"
add("unetWindow", str(_uw.pop()))
add("unetDepths", str(len(un_depths)))


def _un_worth(rows, norm):
    """Reach worth, paired on seed: deepest minus shallowest."""
    out = []
    for sd_ in sorted({r["seed"] for r in rows}):
        a = [r["retrained"] for r in rows
             if r["norm"] == norm and r["seed"] == sd_ and r["depth"] == un_lo]
        b = [r["retrained"] for r in rows
             if r["norm"] == norm and r["seed"] == sd_ and r["depth"] == un_hi]
        if a and b:
            out.append(b[0] - a[0])
    return np.array(out)


un_probs = sorted({r["switch_prob"] for r in un})
un_rows = []
for i, pr in enumerate(un_probs):
    h = [r for r in un if r["switch_prob"] == pr]
    g, q = _un_worth(h, "group"), _un_worth(h, "positionwise")
    sw = np.mean([r["switches_per_window"] for r in h])
    un_rows.append((sw, g, q, q.mean() / g.mean()))
    tag = "Sparse" if i == 0 else "Dense"
    add(f"unetSw{tag}", f"{sw:.2f}")
    add(f"unetGroup{tag}", f"{g.mean():+.4f}")
    add(f"unetGroupSD{tag}", f"{sd(g):.4f}")
    add(f"unetPos{tag}", f"{q.mean():+.4f}")
    add(f"unetPosSD{tag}", f"{sd(q):.4f}")
    add(f"unetRatio{tag}", f"{q.mean() / g.mean():.1f}")

# The test the O(1/|S|) argument actually predicts along: depth is what changes
# how many values the statistic is taken over, so the question is whether the
# sequence-pooled arm degrades with depth, not what the aggregate ratio is.
_sparse = [r for r in un if r["switch_prob"] == un_probs[0]]
_pool = [np.mean([r["retrained"] for r in _sparse
                  if r["norm"] == "group" and r["depth"] == d])
         for d in sorted({r["depth"] for r in _sparse})]
add("unetFlat", f"{max(_pool) - min(_pool):.3f}")
# Positions the statistic pools over at each end of the depth range: L/2^d.
_dlo, _dhi = min(r["depth"] for r in un), max(r["depth"] for r in un)
_W, _WIDTH = int(MACROS["window"]), 64
add("unetDepthLo", str(_dlo))
add("unetDepthHi", str(_dhi))
add("unetPoolHi", str(_W // 2 ** _dlo))
add("unetPoolLo", str(_W // 2 ** _dhi))
add("unetPoolFold", str(2 ** (_dhi - _dlo)))
# |S| at the deepest depth: still thousands of values, which is why the
# magnitude argument does not bite over the range we can test.
add("unetValuesDeep", f"{_WIDTH * _W // 2 ** _dhi:,}".replace(",", "{,}"))

# What the shallowest sequence-pooled model reaches against the two optima, the
# comparison that says it behaves like the summary oracle and not like its own
# receptive field.
add("unetCeiling", f"{np.mean([r['bayes_full_context'] for r in _sparse]):.4f}")
add("unetShallowPooled",
    f"{np.mean([r['retrained'] for r in _sparse if r['norm'] == 'group' and r['depth'] == un_lo]):.4f}")
add("unetShallowLocal",
    f"{np.mean([r['retrained'] for r in _sparse if r['norm'] == 'positionwise' and r['depth'] == un_lo]):.4f}")
# The exact optima at the U-Net's own switch density, so the shallowest
# sequence-pooled model can be read against the proportion oracle rather than
# against the other arm. Matched on switch_prob, not on a tolerance.
_uo = min(load("optima.json"),
          key=lambda r: abs(r["switches_per_window"]
                            - np.mean([x["switches_per_window"] for x in _sparse])))
add("unetOracle", f"{_uo['global_only']:.4f}")
add("unetFull", f"{_uo['full']:.4f}")
# The U-Net's shallowest convolutional reach is 22, which no exact optimum was
# computed at -- they were computed at the dilated stack's reaches. 22 lies
# between 9 and 33, so the honest comparison is the bracket, and the assertion
# below keeps the sentence in Section 5 true if any of these numbers move.
add("unetLocalNine", f"{_uo['local']['9']:.4f}")
add("unetLocalHi", f"{_uo['local']['33']:.4f}")
_upl = np.mean([r["retrained"] for r in _sparse
                if r["norm"] == "positionwise" and r["depth"] == un_lo])
add("unetShallowLocalPct",
    f"{100 * (_upl - _uo['local']['9']) / (_uo['local']['33'] - _uo['local']['9']):.0f}")
assert 9 < _rf(un_lo) < 33, f"reach {_rf(un_lo)} no longer sits between 9 and 33"
assert _uo["local"]["9"] < _upl < _uo["local"]["33"], (
    f"the per-position U-Net ({_upl:.4f}) is no longer bracketed by "
    f"local(9)={_uo['local']['9']:.4f} and local(33)={_uo['local']['33']:.4f}")
add("unetPctOracle",
    f"{100 * np.mean([r['retrained'] for r in _sparse if r['norm'] == 'group' and r['depth'] == un_lo]) / _uo['global_only']:.1f}")

# -------------------------------------- the simulated axis against its source
# The genomic axis was ported from an earlier implementation of the same
# demography, and reproduces its F_ST at every split time. Quoted in Section 4
# so a reader knows the simulator is not free to be whatever the result needs.
# The source is the bioRxiv preprint cited as tian2026lai.
pc = load("port_check.json")
by_T = [(np.mean([r["fst"] for r in pc if r["split_time"] == T]),
         next(r["fst_reference"] for r in pc if r["split_time"] == T))
        for T in sorted({r["split_time"] for r in pc})]
add("portLevels", str(len(by_T)))
add("portMaxDiff", f"{max(abs(a - b) for a, b in by_T):.4f}")
add("portMaxRel", f"{100 * max(abs(a - b) / b for a, b in by_T):.0f}")
add("portFstLo", f"{min(b for _, b in by_T):.4f}")

# ------------------------------------------- the bounded-reach optimum, closed
# R positions sharing a label give an effective separation sqrt(R)*delta, so the
# bounded-reach optimum is Phi(sqrt(R)*delta/2) while runs are long. Reported
# because it agrees with the forward-backward computation, which is an
# independent check on the latter.
from math import erf, sqrt, pi                                       # noqa: E402

Phi = lambda z: 0.5 * (1 + erf(z / sqrt(2)))
_op = load("optima.json")
_sparse = _op[0]
_delta = _sparse["delta"]
_Rs = sorted(int(k) for k in _sparse["local"])
_err = {R: Phi(sqrt(R) * _delta / 2) - _sparse["local"][str(R)] for R in _Rs}
add("closedRmax", str(max(R for R in _Rs if abs(_err[R]) < 0.005)))
add("closedErr", f"{max(abs(_err[R]) for R in _Rs if abs(_err[R]) < 0.005):.4f}")
add("closedNine", f"{Phi(sqrt(9) * _delta / 2):.4f}")
add("closedFar", f"{Phi(sqrt(2049) * _delta / 2):.3f}")
add("synDelta", f"{_delta:.2f}")
add("perPosBayes", f"{Phi(_delta / 2):.4f}")
# The matched pair on the ancestry process: what the per-position control
# reaches at the two ends of the sweep, at the level delta was matched to.
_m = [r for r in tr if r["split_time"] == 400 and r["norm"] == "positionwise"]
add("genLoAcc", f"{np.mean([r['retrained'] for r in _m if r['prefix'] == 1]):.3f}")
add("genHiAcc", f"{np.mean([r['retrained'] for r in _m if r['prefix'] == 9]):.3f}")

# ------------------------------------------------------------------ optima
op = load("optima.json")


def near(row, opt):
    """Match a result row to an optima row. Both record the switch probability
    they were generated with, so the match is exact; matching on the realised
    switch count would not be, since that is a per-seed quantity while the
    optima table stores the seed mean."""
    return row["switch_prob"] == opt["switch_prob"]

rows = []
for r in op:
    n = r["switches_per_window"]
    net_p = [x["retrained"] for x in syn if near(x, r)
             and x["norm"] == "positionwise" and x["prefix"] == 1]
    net_g = [x["retrained"] for x in syn if near(x, r)
             and x["norm"] == "group" and x["prefix"] == 1]
    if net_p and net_g:
        rows.append((100 * (np.mean(net_p) - .5) / (r["local"]["9"] - .5),
                     100 * (np.mean(net_g) - .5) / (r["global_only"] - .5)))
add("boundLocalLo", f"{min(p for p, _ in rows):.0f}")
add("boundLocalHi", f"{max(p for p, _ in rows):.0f}")
# The prose places these at the ends of the sweep ("where labels rarely
# switch", "at synNMax"), so they are computed there, not as extrema; the
# asserts keep the placement honest if a regeneration bends the curve.
assert rows[0][1] == max(q for _, q in rows), "oracle share no longer peaks at the sparsest density"
assert rows[-1][1] == min(q for _, q in rows), "oracle share no longer bottoms at the densest density"
add("boundGlobalHi", f"{rows[0][1]:.0f}")
add("boundGlobalLo", f"{rows[-1][1]:.0f}")
add("boundNDensities", str(len(rows)))

# Shortfall of the sequence-pooled network at reach 9 against the proportion
# oracle, at the sparsest and densest settings; quoted in the figure caption.
short = []
for r in op:
    h = [x["retrained"] for x in syn if near(x, r)
         and x["norm"] == "group" and x["prefix"] == 1]
    if h:
        short.append((r["switches_per_window"], r["global_only"] - np.mean(h)))
add("shortSparse", f"{short[0][1]:.3f}")
add("shortDense", f"{short[-1][1]:.3f}")
add("shortWorst", f"{max(s for _, s in short):.3f}")

# What the bounds alone predict for the ratio, against what is measured. The
# idealised constant is not constant, which is why the c/n law is reported as
# an empirical regularity rather than derived.
_ideal = []
for r in op:
    n_ = r["switches_per_window"]
    a_ = r["local"]["9"] - 0.5
    g_ = 1 / np.sqrt(2 * np.pi * n_)
    den = (r["full"] - 0.5) - g_
    if g_ > a_ and den > 0:
        _ideal.append(((g_ - a_) / den) * n_)
add("idealCLo", f"{min(_ideal):.1f}")
add("idealCHi", f"{max(_ideal):.1f}")
add("idealCFold", f"{max(_ideal) / min(_ideal):.1f}")

adv = [(r["switches_per_window"], r["global_only"] - 0.5) for r in op]
k = np.array([a * np.sqrt(n) for n, a in adv if n >= 0.9])
add("rootLawK", f"{k.mean():.2f}")
add("rootLawSpread", f"{100 * sd(k) / k.mean():.0f}")

# Where the networks land against the bounds, at *every* reach rather than only
# the shortest. local(R) is computed as a blocked bound and so is conservative;
# cells where the network exceeds it are evidence the bound is tight, not that
# the network beat the optimum.
resid = []
for r in op:
    n = r["switches_per_window"]
    for kk in (1, 3, 5, 7, 9):
        h = [x["retrained"] for x in syn if near(x, r)
             and x["norm"] == "positionwise" and x["prefix"] == kk]
        if h:
            resid.append(np.mean(h) - r["local"][str(1 + 4 * sum([1, 2, 4, 8, 16,
                                                                  32, 64, 128,
                                                                  256][:kk]) + 4)])
resid = np.array(resid)
add("boundAllCells", str(len(resid)))
add("boundAllMean", f"{np.abs(resid).mean():.3f}")
add("boundAllAbove", str(int((resid > 0).sum())))
# How far above, so the text can say the exceedances are small rather than
# asking the reader to take the bound's conservatism on trust.
add("boundAllAboveMax", f"{resid.max():.4f}")
# At the shortest reach the same agreement stated in raw accuracy: the share
# scale is the strict one, and quoting only "98--99%" reads looser than it is.
_short_raw = []
for r in op:
    h = [x["retrained"] for x in syn if near(x, r)
         and x["norm"] == "positionwise" and x["prefix"] == 1]
    if h:
        _short_raw.append(r["local"]["9"] - np.mean(h))
add("boundLocalRawMax", f"{max(_short_raw):.4f}")
# The ignoring-hypothesis dies on the numbers alone: no predictor confined to
# reachMin positions can be this far above the exact optimum for that reach,
# and the bound's largest observed slack is orders of magnitude too small.
_excess = []
for r in op:
    h = [x["retrained"] for x in syn if near(x, r)
         and x["norm"] == "group" and x["prefix"] == 1]
    if h:
        _excess.append(np.mean(h) - r["local"]["9"])
# Quoted as the excess at the sparsest density; assert it is also the grid
# maximum, which is what makes "anywhere in the grid" phrasing safe elsewhere.
assert _excess[0] == max(_excess), "group excess no longer largest at the sparsest density"
add("boundGroupExcess", f"{_excess[0]:.2f}")
add("boundExcessFold", f"{_excess[0] / resid.max():.0f}")

# ------------------------------------------------- the law's exponent, fitted
def power_fit(pairs):
    """log(ratio - 1) = log c - alpha log n; returns alpha, its s.e., R^2."""
    x = np.log([n for n, _ in pairs])
    y = np.log([r - 1 for _, r in pairs])
    A = np.vstack([x, np.ones_like(x)]).T
    coef, *_ = np.linalg.lstsq(A, y, rcond=None)
    pred = A @ coef
    r2 = 1 - ((y - pred) ** 2).sum() / ((y - y.mean()) ** 2).sum()
    se = np.sqrt(((y - pred) ** 2).sum() / (len(x) - 2)
                 / ((x - x.mean()) ** 2).sum())
    return -coef[0], se, r2


a, se, r2 = power_fit(sd_)
add("lawAlphaSyn", f"{a:.2f}")
add("lawAlphaSynSE", f"{se:.2f}")
add("lawAlphaSynR", f"{r2:.3f}")
a, se, _ = power_fit(gd)
add("lawAlphaGen", f"{a:.2f}")
add("lawAlphaGenSE", f"{se:.2f}")
add("lawFold", f"{c.max() / c.min():.1f}")
add("lawRootFold", f"{croot.max() / croot.min():.0f}")
add("synSpanRatio", f"{max(r - 1 for _, r in sd_) / min(r - 1 for _, r in sd_):.0f}")
add("genSpanRatio", f"{max(r - 1 for _, r in gd) / min(r - 1 for _, r in gd):.0f}")

# ------------------------------------- ablation vs retraining, pooled and cut
def costs(rows, norm, k):
    h = [r for r in rows if r["norm"] == norm and r["prefix"] == k]
    return (np.mean([r["cost_ablated"] for r in h]),
            np.mean([r["cost_retrained"] for r in h]))


for norm, tag in (("group", "Open"), ("positionwise", "Closed")):
    for k, suffix in ((1, ""), (3, "Cut")):
        a_, r_ = costs(tr, norm, k)
        add(f"ablCost{tag}{suffix}", f"{a_:.4f}")
        add(f"retCost{tag}{suffix}", f"{r_:.4f}")
        add(f"ablRatio{tag}{suffix}", f"{a_ / r_:.1f}")

# Retention at the cut that removes every block with dilation >= 8, which is
# the cut such analyses usually report.
cut = [r for r in tr if r["norm"] == "group" and r["prefix"] == 3]
by_T = lambda key, T: np.mean([r[key] for r in cut if r["split_time"] == T
                               and not np.isnan(r[key])])
sd_by_T = lambda key, T: sd([r[key] for r in cut if r["split_time"] == T
                             and not np.isnan(r[key])])
add("cutAblRet", f"{np.mean([by_T('retention_ablated', T) for T in levels]):.3f}")
add("cutRetRet", f"{np.mean([by_T('retention_retrained', T) for T in levels]):.3f}")
add("cutAblSD", f"{np.mean([sd_by_T('retention_ablated', T) for T in levels]):.3f}")
add("cutRetSD", f"{np.mean([sd_by_T('retention_retrained', T) for T in levels]):.3f}")
add("cutAblHi", f"{by_T('retention_ablated', levels[0]):.2f}")
add("cutAblLo", f"{by_T('retention_ablated', levels[-1]):.2f}")
add("cutRetHi", f"{by_T('retention_retrained', levels[0]):.2f}")
add("cutRetLo", f"{by_T('retention_retrained', levels[-1]):.2f}")
add("cutNoiseFold", f"{np.mean([sd_by_T('retention_ablated', T) for T in levels]) / np.mean([sd_by_T('retention_retrained', T) for T in levels]):.0f}")

# The discrepancy as a function of the pooling axis: the causal test.
DISS = [("none", "---", "disNone"), ("positionwise", "channels", "disPos"),
        ("batch", "batch and length, running at eval", "disBatch"),
        ("instance", "length", "disInst"),
        ("group", "channels and length", "disGroup")]
diss_rows = []
for key, axes_, macro in DISS:
    h = [r for r in nm if r["norm"] == key and r["prefix"] == 1]
    a_ = np.mean([r["full"] - r["ablated"] for r in h])
    r_ = np.mean([r["full"] - r["retrained"] for r in h])
    add(macro, f"{a_ / r_:.1f}")
    diss_rows.append((key, axes_, a_, r_, a_ / r_))
add("disClosedLo", f"{min(x[4] for x in diss_rows[:3]):.1f}")
add("disClosedHi", f"{max(x[4] for x in diss_rows[:3]):.1f}")
add("disOpenLo", f"{min(x[4] for x in diss_rows[3:]):.1f}")
add("disOpenHi", f"{max(x[4] for x in diss_rows[3:]):.1f}")
# The factor between the two bands' means, quoted in Section 6 as a word.
add("disBandFold", WORDS[round(np.mean([x[4] for x in diss_rows[3:]])
                               / np.mean([x[4] for x in diss_rows[:3]]))])

# Accuracies at the extremes of the difficulty sweep, for a concrete sentence.
def acc(T, norm, k):
    return np.mean([r["retrained"] for r in tr if r["split_time"] == T
                    and r["norm"] == norm and r["prefix"] == k])


# The Introduction's concrete illustration, taken from the sparsest density of the
# synthetic process so that every number in it is visible in Figure 1. Reading it
# off a different process meant citing a second figure the reader had not reached.
_i0 = op[0]
_ih = [x["retrained"] for x in syn if x["switch_prob"] == _i0["switch_prob"]
       and x["norm"] == "group" and x["prefix"] == 1]
add("introNet", f"{np.mean(_ih):.3f}")
add("introLocal", f"{_i0['local']['9']:.3f}")
add("introOracle", f"{_i0['global_only']:.3f}")
# The full-context optimum and the shortfall against it are separate macros,
# although at this density they print identically to the proportion-oracle
# ones: the coincidence is a fact of the sparse regime, not of the code, and
# prose about the whole-sequence optimum must not quote the oracle's field.
add("introFull", f"{_i0['full']:.3f}")
add("shortSparseFull", f"{_i0['full'] - np.mean(_ih):.3f}")
add("accEasyPooled", f"{acc(levels[0], 'group', 1):.3f}")
add("accEasyLocal", f"{acc(levels[0], 'positionwise', 1):.3f}")
# "The control needs this many positions to match it": true only while the
# per-position control at the previous reach still falls short of the pooled
# model at reach 9 and the control at this reach does not.
assert acc(levels[0], "positionwise", 3) < acc(levels[0], "group", 1) <= acc(levels[0], "positionwise", 5), \
    "the 129-position catch-up claim no longer holds on the easiest level"
add("accEasyLocalCaught", str(1 + 4 * sum([1, 2, 4, 8, 16]) + 4))
add("accHardPooled", f"{acc(levels[-1], 'group', 1):.3f}")
add("accHardLocal", f"{acc(levels[-1], 'positionwise', 1):.3f}")

# The dissection table goes in the main text, so it is written separately.
DISSECT = Path("paper/table_dissect.tex")
DISSECT.write_text(
    "% Generated by paper/make_numbers.py. Do not edit.\n"
    "\\begin{tabular}{llrrr}\n\\toprule\n"
    "normalization & statistics pooled over & by ablation & by retraining "
    "& ratio \\\\\n\\midrule\n"
    + "".join(
        f"{k.replace('positionwise', 'per position')} & {a} & "
        f"${x:+.4f}$ & ${y:+.4f}$ & ${z:.1f}$ \\\\\n"
        for k, a, x, y, z in diss_rows)
    + "\\bottomrule\n\\end{tabular}\n")

OUT.write_text(HEADER + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n"
                                for k, v in sorted(MACROS.items())))
print(f"wrote {OUT} with {len(MACROS)} macros")

# ------------------------------------------------------- appendix tables
# ------------------------------------------------------- appendix-only macros
jc = load("jacobian_check.json")
add("jacS", str(jc["set_size"]))
add("jacC", str(jc["channels"]))
add("jacL", str(jc["positions"]))
add("jacErr", f"{jc['gln']['max_abs_error']:.1e}".replace("e-16", r"\times 10^{-16}"))
add("jacOffdiag", f"{jc['gln']['mean_abs_offdiag']:.4f}")
add("jacInvS", f"{jc['gln']['one_over_S']:.4f}")
add("jacDiag", f"{jc['gln']['diagonal']:.4f}")
add("jacRowsum", f"{jc['gln']['row_sum_offdiag']:.4f}")
add("jacRowTotal", f"{abs(jc['gln']['diagonal'] + jc['gln']['row_sum_offdiag']):.0e}"
    .replace("e-17", r"\times 10^{-17}").replace("e-16", r"\times 10^{-16}"))
add("jacClnPast", f"{jc['cln']['max_abs_past']:.4f}")

# --------------------------------------------- the premise that did not hold
nd = load("null_deff.json")
_Ts = sorted({r["split_time"] for r in nd}, reverse=True)


def _deff(T):
    g = [r for r in nd if r["split_time"] == T]
    obs = np.array([r["d_eff"] for r in g])
    nul = np.concatenate([r["d_eff_crossseed"] for r in g])
    return obs.mean(), nul.mean(), (obs.mean() - nul.mean()) / nul.std()


_obs = [_deff(T) for T in _Ts]
add("deffLevels", str(len(_Ts)))
add("deffObsEasy", f"{_obs[0][0]:.1f}")
add("deffObsHard", f"{_obs[-1][0]:.1f}")
add("deffObsPeak", f"{max(o for o, _, _ in _obs):.1f}")
add("deffPeakT", str(_Ts[int(np.argmax([o for o, _, _ in _obs]))]))
add("deffNullEasy", f"{_obs[0][1]:.1f}")
add("deffNullHard", f"{_obs[-1][1]:.1f}")
add("deffMarginMax", f"{max(m for _, _, m in _obs):.1f}")

sn = load("shift_null.json")
# The shift leaves untouched exactly the single-label sequences; the appendix
# says so, so check it here rather than trusting it.
assert max(abs(r["frac_single_label"] - r["frac_vectors_unchanged"])
           for r in sn) < 1e-12, "shift touches some single-label sequence"
_es = load("exposure_survey.json")
# Spelled out: these appear mid-sentence, and the unexposed count in particular
# had already gone stale once when a domain was added.
_WORD = {2: "Two", 4: "four", 9: "nine", 11: "eleven", 13: "thirteen"}
_nex = sum(m["exposed"] for m in _es["models"])
add("surveyN", _WORD[len(_es["models"])])
add("surveyExposed", _WORD[_nex])
add("surveyExposedLc", _WORD[_nex].lower())
add("surveyUnexposed", _WORD[len(_es["models"]) - _nex])
add("surveyDomains", _WORD[len({m["domain"] for m in _es["models"]})])
# Named, not just counted: a reviewer asked that the spread of fields be visible
# in the contributions rather than left to the table.
_doms = sorted({m["domain"] for m in _es["models"]})
add("surveyDomainList", ", ".join(_doms[:-1]) + " and " + _doms[-1])
add("shiftSingle", f"{100 * np.mean([r['frac_single_label'] for r in sn]):.0f}")
add("shiftChanged", f"{100 * np.mean([r['frac_labels_changed'] for r in sn]):.1f}")

# --------------------------------------- the pooled mean literally carries pi
sc = load("signal_check.json")
_ratios = [r["resid_std"] / r["predicted_noise_std"] for r in sc]
add("sigRatioLo", f"{min(_ratios):.2f}")
add("sigRatioHi", f"{max(_ratios):.2f}")
# The prose reports these as the values at the sparsest and densest settings,
# so compute them that way -- means over seeds, as everywhere else in the paper.
# min/max over all cells happened to coincide with the endpoints, but only
# happened to: nothing made the extremes fall there.
_by_n = {}
for r in sc:
    _by_n.setdefault(round(r["switches_per_window"], 2), []).append(r["corr_mu_pred"])
add("sigCorrHi", f"{np.mean(_by_n[min(_by_n)]):.2f}")
add("sigCorrLo", f"{np.mean(_by_n[max(_by_n)]):.2f}")
add("sigCells", str(len(sc)))
add("sigDensities", str(len(SWITCH_PROBS_SIG := sorted({r["switch_prob"] for r in sc}))))

TABLES = Path("paper/tables.tex")
lines = []


def table(label, caption, header, rows, spec, env="table", placement="[t]"):
    """env="sidewaystable" turns the float on its side, for the one table whose
    natural width does not fit the text block. It needs \\usepackage{rotating},
    and takes no placement argument."""
    if env == "sidewaystable":
        placement = ""
    # Elsevier's text block is narrower than TMLR's, and several of these grids
    # are wider than it. Wrapping in \resizebox shrinks only the ones that would
    # otherwise run into the margin: \textwidth is a maximum, not a target,
    # because the box keeps its natural size when that is already smaller.
    lines.append(f"\\begin{{{env}}}{placement}\n" r"\centering" "\n"
                 f"\\caption{{{caption}}}\n\\label{{{label}}}\n"
                 r"\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{%" "\n"
                 f"\\begin{{tabular}}{{{spec}}}\n\\toprule\n"
                 + " & ".join(header) + r" \\" "\n\\midrule\n"
                 + "".join(" & ".join(r) + r" \\" "\n" for r in rows)
                 + f"\\bottomrule\n\\end{{tabular}}}}\n\\end{{{env}}}\n")


# --- appendix: the full reach grid, which the main text only summarizes
DIL = (1, 2, 4, 8, 16, 32, 64, 128, 256)
rf = lambda k, per=4: 1 + per * sum(DIL[:k]) + 4
ks = sorted({r["prefix"] for r in tr})
rows = []
for norm, lab in (("group", "pooled over length"), ("positionwise", "per position")):
    for i, T in enumerate(levels):
        h = [r for r in tr if r["split_time"] == T and r["norm"] == norm]
        rows.append([lab if i == 0 else "",
                     f"{np.mean([r['fst'] for r in h]):.4f}"]
                    + [f"{np.mean([r['retrained'] for r in h if r['prefix'] == k]):.4f}"
                       for k in ks])
table("tab:grid",
      "Held-out accuracy of networks retrained with the first $k$ blocks, by "
      "divergence level and normalization. The columns are receptive fields in "
      "positions. Means over \\nSeeds\\ seeds; this is the grid behind "
      "Figure~\\ref{fig:reach}a and Table~\\ref{tab:difficulty}.",
      ["normalization", "$F_{ST}$"] + [f"$R={rf(k)}$" for k in ks],
      rows, "ll" + "r" * len(ks))

# Reach worth by difficulty.
rows = []
for T in levels:
    h = [r for r in tr if r["split_time"] == T]
    g, q = reach_worth(h, "group", 1, 9), reach_worth(h, "positionwise", 1, 9)
    rows.append([f"{np.mean([r['fst'] for r in h]):.4f}",
                 f"${g.mean():+.4f} \\pm {sd(g):.4f}$",
                 f"${q.mean():+.4f} \\pm {sd(q):.4f}$",
                 f"{q.mean() / g.mean():.1f}"])
table("tab:difficulty",
      "Reach worth at each divergence level of the simulated genomes, with "
      "statistics pooled along the sequence and per position. Their ratio, "
      "per position over pooled, does not vary systematically with difficulty.",
      [r"$F_{ST}$", "pooled over length", "per position", "ratio"],
      rows, "lrrr")

# Dose-response, both processes and real data, with both terms of the ratio.
def worth_pair(rows_, sel):
    h = [r for r in rows_ if sel(r)]
    ks = sorted({r["prefix"] for r in h})
    g = reach_worth(h, "group", ks[0], ks[-1])
    q = reach_worth(h, "positionwise", ks[0], ks[-1])
    return (f"${g.mean():+.4f} \\pm {sd(g):.4f}$",
            f"${q.mean():+.4f} \\pm {sd(q):.4f}$", q.mean() / g.mean())


rows = []
for i, g_ in enumerate(sorted({r["generations"] for r in gen})):
    n = np.mean([r["switches_per_window"] for r in gen if r["generations"] == g_])
    a, b, q = worth_pair(gen, lambda r, v=g_: r["generations"] == v)
    rows.append(["genomic" if i == 0 else "", f"{n:.2f}", a, b,
                 f"{q:.1f}", f"{(q - 1) * n:.2f}"])
for i, p_ in enumerate(sorted({r["switch_prob"] for r in syn})):
    n = np.mean([r["switches_per_window"] for r in syn if r["switch_prob"] == p_])
    a, b, q = worth_pair(syn, lambda r, v=p_: r["switch_prob"] == v)
    rows.append(["synthetic" if i == 0 else "", f"{n:.2f}", a, b,
                 f"{q:.1f}", f"{(q - 1) * n:.2f}"])
n = np.mean([r["switches_per_window"] for r in rl])
a, b, q = worth_pair(rl, lambda r: True)
rows.append(["real 1000G", f"{n:.2f}", a, b, f"{q:.1f}",
             f"{(q - 1) * n:.2f}"])
table("tab:dose",
      "Switch-rate dose--response on both simulated processes and on real "
      "haplotypes. Both middle columns are the accuracy gained by the "
      "\\reachFold-fold enlargement of the receptive field; the last column is the "
      "constant of the $c/n$ regularity at each density. It is flat within "
      "each process and differs between them.",
      ["process", "$n$", "pooled over length", "per position", "ratio",
       r"$(\text{ratio}-1)\,n$"], rows, "llccrr")

# --- appendix: Conv-TasNet, which the main text gives only as two endpoints
tks = sorted({r["prefix"] for r in tn})
rows = []
for key, lab, axes_ in (("gln", "gLN", "channels and time"),
                        ("cln", "cLN", "channels and time up to $t$"),
                        ("gln_pos", "per position", "channels")):
    rows.append([lab, axes_]
                + [f"{np.mean([r['retrained'] for r in tn if r['norm'] == key and r['prefix'] == k]):.4f}"
                   for k in tks])
table("tab:tasnet",
      "The Conv-TasNet separator on the synthetic process at "
      f"{np.mean([r['switches_per_window'] for r in tn]):.2f} switches per "
      "sequence, against an exact whole-sequence optimum of "
      f"{np.mean([r['bayes_full_context'] for r in tn]):.4f}. Its depthwise "
      "kernel is 3, so a block adds $2d$ rather than $4d$ and the receptive "
      "fields differ from the other tables. Means over \\nSeeds\\ seeds.",
      ["layer", "statistics pooled over"] + [f"$R={rf(k, 2)}$" for k in tks],
      rows, "ll" + "r" * len(tks))

# --- appendix: the transformer, given in the main text only as a range
rows = []
for p_ in sorted({r["switch_prob"] for r in tf}):
    h = [r for r in tf if r["switch_prob"] == p_]
    a = np.mean([r["retrained"] for r in h if r["norm"] == "group"])
    b = np.mean([r["retrained"] for r in h if r["norm"] == "positionwise"])
    c_ = np.mean([r["bayes_full_context"] for r in h])
    # The shortfall is a column rather than a subtraction the reader performs:
    # from the rounded accuracies it comes out a digit different from the
    # unrounded one the main text quotes.
    rows.append([f"{np.mean([r['switches_per_window'] for r in h]):.2f}",
                 f"{a:.4f}", f"{b:.4f}", f"{a - b:+.4f}", f"{c_:.4f}",
                 f"{c_ - max(a, b):.4f}"])
table("tab:transformer",
      "(P4) A transformer, whose attention spans the input sequence at every depth, "
      "with sequence-pooled and with per-position normalization. The two are "
      "within a few thousandths of each other and of the exact optimum at "
      "every switch density: with the context already available there is "
      "nothing for the path to supply. The last column is the better of the "
      "two normalizations against the optimum, and the range the main text "
      "quotes is the widest of these. Means over \\nSeeds\\ seeds.",
      ["switches per sequence", "pooled over length", "per position",
       "difference", "exact optimum", "shortfall"], rows, "rrrrrr")

# --- appendix: the grid behind the "networks sit at their own bound" claim.
# Residuals rather than accuracies, because every figure the main text quotes
# is a residual, and a reader who reconstructs them by subtracting rounded
# accuracies can land a digit off the unrounded value.
_RK = [(kk, 1 + 4 * sum([1, 2, 4, 8, 16, 32, 64, 128, 256][:kk]) + 4)
       for kk in (1, 3, 5, 7, 9)]
rows = []
for r in sorted(op, key=lambda r: r["switches_per_window"]):
    cells = []
    for kk, R in _RK:
        h = [x["retrained"] for x in syn if near(x, r)
             and x["norm"] == "positionwise" and x["prefix"] == kk]
        cells.append(f"{np.mean(h) - r['local'][str(R)]:+.4f}" if h else "---")
    rows.append([f"{r['switches_per_window']:.2f}"] + cells)
table("tab:resid",
      "Per-position networks against the local bound for their own receptive "
      "field, on the synthetic process: each entry is held-out accuracy minus "
      "that bound, so zero is the bound and positive is above it. This is the "
      "grid behind every number quoted in Section~\\ref{sec:tests} for this "
      "comparison: \\boundAllCells\\ cells, mean absolute value \\boundAllMean, "
      "\\boundAllAbove\\ of them positive, the largest \\boundAllAboveMax. "
      "Exceedances are expected, since $\\mathrm{local}(R)$ is a blocked bound "
      "and therefore conservative, and the entries are finite-sample means "
      "(Section~\\ref{sec:setup}). Adding the "
      "corresponding entry of Table~\\ref{tab:optima} recovers the accuracy "
      "itself. Means over \\nSeeds\\ seeds.",
      ["switches/sequence"] + [f"$R={R}$" for _, R in _RK], rows,
      "r" * (len(_RK) + 1))

# Exact optima.
# Every reach that was computed, not just the two ends: the main text reads
# values off the intermediate ones -- local(33) brackets the U-Net's reach and
# local(129) is where the per-position control draws level -- and a claim the
# reader cannot check against the table is a claim taken on trust.
_reaches = sorted(op[0]["local"], key=int)
rows = []
for r in op:
    rows.append([f"{r['switches_per_window']:.2f}"]
                + [f"{r['local'][k]:.4f}" for k in _reaches]
                + [f"{r['full']:.4f}", f"{r['global_only']:.4f}"])
table("tab:optima",
      "The reference values on the synthetic process: the local bound at "
      "every receptive field it was computed for, and the exactly computed "
      "optima with full context and with an "
      "oracle given only the sequence's class proportion. The intermediate "
      "columns are here because the main text reads values off them: "
      "$R=33$ brackets the U-Net's receptive field (Section~\\ref{sec:tests}) and "
      "$R=129$ is where the per-position control matches a "
      "sequence-pooled model at $R=9$ (Section~\\ref{sec:tests}).",
      ["switches"] + [f"$R={k}$" for k in _reaches]
      + ["full", "proportion oracle"], rows,
      "r" * (len(_reaches) + 3))





# --- appendix: the port check, which Setup asserts in one sentence
rows = [[str(T),
         f"{np.mean([r['fst'] for r in pc if r['split_time'] == T]):.4f}",
         f"{next(r['fst_reference'] for r in pc if r['split_time'] == T):.4f}",
         f"{np.mean([r['fst'] for r in pc if r['split_time'] == T]) - next(r['fst_reference'] for r in pc if r['split_time'] == T):+.4f}",
         f"{np.mean([r['accuracy'] for r in pc if r['split_time'] == T]):.4f}"]
        for T in sorted({r["split_time"] for r in pc}, reverse=True)]
table("tab:port",
      "The simulated ancestry process against the benchmark it was ported from "
      "\\citep{tian2026lai}, at all eight of its split times. $F_{ST}$ is "
      "measured from the simulated panels rather than set, so agreement is a "
      "check on the demography, the coalescent draw and the estimator "
      "together. Accuracy is the reference architecture's, over \\nSeeds\\ seeds.",
      ["split time", "$F_{ST}$, ours", "$F_{ST}$, benchmark", "difference",
       "accuracy"], rows, "rrrrr")

# --- appendix: the U-Net depth sweep
rows = []
for i, pr in enumerate(un_probs):
    h = [r for r in un if r["switch_prob"] == pr]
    sw = np.mean([r["switches_per_window"] for r in h])
    for j, d in enumerate(un_depths):
        cell = lambda nmm: np.mean([r["retrained"] for r in h
                                    if r["norm"] == nmm and r["depth"] == d])
        rows.append([f"{sw:.2f}" if j == 0 else "", str(d),
                     str(_rf(d)), f"{cell('group'):.4f}",
                     f"{cell('positionwise'):.4f}"])
table("tab:unet",
      "The U-Net depth sweep on the synthetic process, at \\unetDepths\\ depths "
      "and two switch densities, means over \\nSeeds\\ seeds. ``Receptive "
      "field'' is the convolutional span, measured by autograd rather than "
      "derived; with statistics pooled along the sequence the same measurement "
      "returns \\unetWindow\\ at every depth, which is the whole sequence. Depth "
      "is what sets the receptive field here, and it also sets how many values each "
      "normalization statistic is taken over, so this is the one architecture "
      "in which the two cannot be varied separately.",
      ["switches/sequence", "depth", "receptive field",
       "pooled over length", "per position"], rows, "rrrrr")

# --- appendix: the normalization survey of published models
es = load("exposure_survey.json")
rows = []
for m in es["models"]:
    rows.append([m["domain"],
                 m["model"].replace("&", "\\&") + f" \\citep{{{m['cite']}}}",
                 m["short"].replace("_", "\\_"),
                 r"\textbf{yes}" if m["exposed"] else "no"])
_nex = sum(m["exposed"] for m in es["models"])
_ndom = len({m["domain"] for m in es["models"]})
_num = {2: "Two", 3: "Three"}[_nex]
table("tab:survey",
      f"Normalization configurations of {len(es['models'])} published "
      f"sequence-labeling models across {_ndom} domains whose labels come in "
      "long runs, read from each project's source rather than from its paper. "
      "``Exposed'' means the criterion of Section~\\ref{sec:theory} is met: "
      "statistics computed from the current input, along the sequence, at "
      f"inference. {_num} are. Citations are to each model's publication; the "
      "evidence for the row is the code, since the two can disagree "
      "(Section~\\ref{sec:discussion}). Each row's source link, pinned to the "
      "commit that was read, and its provenance are in the released "
      "\\texttt{exposure\\_survey.json}.",
      ["domain", "model", "normalization", "exposed"], rows, "lllc",
      env="sidewaystable")

# --- appendix: the per-level costs behind Section 6's pooled ablation numbers.
# The pooled means (ablCostOpen etc.) appear in no figure: Figure 4a is one
# divergence level and Figure 4b a different cut, so without this grid the
# section's headline ratio is uncheckable.
_tr = load("tradeoff.json")
rows = []
for norm, lab in (("group", "pooled over length"),
                  ("positionwise", "per position")):
    for j, T in enumerate(sorted({r["split_time"] for r in _tr}, reverse=True)):
        h = [r for r in _tr if r["split_time"] == T and r["prefix"] == 1
             and r["norm"] == norm]
        a_ = np.mean([r["cost_ablated"] for r in h])
        r_ = np.mean([r["cost_retrained"] for r in h])
        rows.append([lab if j == 0 else "",
                     f"{np.mean([r['fst'] for r in h]):.4f}",
                     f"{a_:.4f}", f"{r_:.4f}", f"{a_ / r_:.1f}"])
table("tab:ablcost",
      "Accuracy lost by removing the long-range blocks (those that enlarge the "
      "receptive field; Section~\\ref{sec:setup}), per divergence level "
      "and normalization: ablating them from the trained network against "
      "retraining without them. The pooled figures of "
      "Section~\\ref{sec:ablation} are means over these rows: \\ablCostOpen\\ "
      "against \\retCostOpen\\ (ratio \\ablRatioOpen) with statistics pooled "
      "along the sequence, and a ratio of \\ablRatioClosed\\ per position. "
      "Means over \\nSeeds\\ seeds.",
      ["normalization", "$F_{ST}$", "ablated", "retrained", "ratio"],
      rows, "llrrr")

TABLES.write_text(HEADER + "\n".join(lines))
print(f"wrote {TABLES} with {len(lines)} tables")

# ------------------------------------------ derivation against measurement
MACROS.clear() if False else None
_extra = {}
adv_rows = []
for r in op:
    n = r["switches_per_window"]
    adv_rows.append((n, r["global_only"] - 0.5, 1 / np.sqrt(2 * np.pi * n)))
# Section 3 argues the approximation must fail below n ~ 1, where pi-bar
# saturates; the threshold is that stated boundary, not a tuned cutoff. An
# earlier n >= 3 filter dropped the n = 2.98 density by 0.02 and so reported
# the range as starting at 6.0, understating where the closed form holds.
big = [(n, a, q) for n, a, q in adv_rows if n >= 1]
err = [abs(a - q) / q for _, a, q in big]
_extra["derivMaxErr"] = f"{100 * max(err):.0f}"
_extra["derivNMin"] = f"{min(n for n, _, _ in big):.1f}"
_extra["derivConst"] = f"{1 / np.sqrt(2 * np.pi):.3f}"
n10 = min(big, key=lambda t: abs(t[0] - 10))
_extra["derivAtTenN"] = f"{n10[0]:.1f}"
_extra["derivAtTenObs"] = f"{n10[1]:.4f}"
_extra["derivAtTenPred"] = f"{n10[2]:.4f}"
for k, v in _extra.items():
    add(k, v)

OUT.write_text(HEADER + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n"
                                for k, v in sorted(MACROS.items())))

lines2 = []
rows = [[f"{n:.2f}", f"{a:.4f}", f"{q:.4f}",
         f"{100 * (a - q) / q:+.0f}\\%"] for n, a, q in adv_rows]
lines2.append(r"\begin{table}[t]" "\n" r"\centering" "\n"
              "\\caption{The derived advantage of an oracle given the sequence's "
              "class proportion, $1/\\sqrt{2\\pi n}$, against the value computed "
              "exactly. No quantity is fitted. The approximation requires "
              "$n \\gg 1$ and $p \\ll 1$ (Section~\\ref{sec:theory}) and fails "
              "below $n \\approx 1$ because $\\bar\\pi$ is bounded in "
              "$[0,1]$.}\n\\label{tab:deriv}\n"
              "\\begin{tabular}{rrrr}\n\\toprule\n"
              "switches per sequence & computed & $1/\\sqrt{2\\pi n}$ & error \\\\\n"
              "\\midrule\n"
              + "".join(" & ".join(r) + r" \\" "\n" for r in rows)
              + "\\bottomrule\n\\end{tabular}\n\\end{table}\n")
TABLES.write_text(TABLES.read_text() + "\n" + "\n".join(lines2))
print("added derivation macros and table")
